apiVersion: v1
name: techtrends
description: A Helm chart to template and deploy the TechTrends application
keywords:
- techtrends
version: 1.0.0
maintainers:
- name: Hari Kishan Dande
  email: harikishan.dande@gmail.com
